stages:
  - test
  - build
 
variables:
  BINARY_NAME: "conCat"     

test:
  stage: test
  image: golang:1.22.1-alpine
  tags:
    - sysadmin_test

  script:
    - echo "Running tests..."
    - go mod download
    - go mod tidy
    - export GOINSECURE=gitlab1.smd.local
    - go generate ./...
    - go test -v -race -coverprofile=coverage-internal.txt $(go list ./internal/... | grep -v /core)
